version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
