run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
